# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-12-14 14:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0001_initial'),
        ('profiles', '0001_initial'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pathalogy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('working_since', models.IntegerField(default=1)),
                ('is_sponsered', models.BooleanField(default=True)),
                ('percent', models.FloatField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Contacts')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TestRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conducted_on', models.DateTimeField(default=datetime.datetime.now)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor')),
                ('pathology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostic.Pathalogy')),
                ('tests', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostic.Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.User')),
            ],
        ),
        migrations.AddField(
            model_name='pathalogy',
            name='test_supported',
            field=models.ManyToManyField(blank=True, to='diagnostic.Test'),
        ),
    ]
